from datetime import datetime

class dateStr(float):
    def __new__(cls, content):
        try:
            value = datetime.strptime(content, "%Y-%m-%dT%H:%M:%S.%fZ")
        except:
            value = datetime.strptime(content, "%Y-%m-%dT%H:%M:%SZ")
        return value

GLOBAL_PROPERTIES ={'DataSource': str,
                    'DataRecorder': str,
                    'ReferenceTime': dateStr,
                    'RecordingTime': dateStr,
                    'Author': str,
                    'Title': str,
                    'Category': str,
                    'Briefing': str,
                    'Debriefing': str,
                    'Comments': str,
                    'ReferenceLongitude': float,
                    'ReferenceLatitude': float}

OBJECT_PROPERTIES ={'Category': str,
                    'Briefing': str,
                    'Debriefing': str,
                    'Name': str,
                    'Type': str,
                    'AdditionalType': str,
                    'Parent': str,
                    'Next': str,
                    'ShortName': str,
                    'LongName': str,
                    'FullName': str,
                    'CallSign': str,
                    'Registration': str,
                    'Squawk': str,
                    'ICAO24': str,
                    'Pilot': str,
                    'Group': str,
                    'Country': str,
                    'Coalition': str,
                    'Color': str,
                    'Shape': str,
                    'Debug': str,
                    'Label': str,
                    'FocusedTarget': str,
                    'LockedTarget': str,
                    'Importance': float,
                    'Slot': float,
                    'Disabled': float,
                    'Visible': float,
                    'Health': float,
                    'Length': float,
                    'Width': float,
                    'Height': float,
                    'Radius': float,
                    'IAS': float,
                    'CAS': float,
                    'TAS': float,
                    'Mach': float,
                    'AOA': float,
                    'AOS': float,
                    'AGL': float,
                    'HDG': float,
                    'HDM': float,
                    'Throttle': float,
                    'Afterburner': float,
                    'AirBrakes': float,
                    'Flaps': float,
                    'LandingGear': float,
                    'LandingGearHandle': float,
                    'Tailhook': float,
                    'Parachute': float,
                    'DragChute': float,
                    'FuelWeight': float,
                    'FuelWeight1': float,
                    'FuelWeight2': float,
                    'FuelWeight3': float,
                    'FuelWeight4': float,
                    'FuelWeight5': float,
                    'FuelWeight6': float,
                    'FuelWeight7': float,
                    'FuelWeight8': float,
                    'FuelWeight9': float,
                    'FuelVolume': float,
                    'FuelVolume1': float,
                    'FuelVolume2': float,
                    'FuelVolume3': float,
                    'FuelVolume4': float,
                    'FuelVolume5': float,
                    'FuelVolume6': float,
                    'FuelVolume7': float,
                    'FuelVolume8': float,
                    'FuelVolume9': float,
                    'FuelFlowWeight': float,
                    'FuelFlowWeight1': float,
                    'FuelFlowWeight2': float,
                    'FuelFlowWeight3': float,
                    'FuelFlowWeight4': float,
                    'FuelFlowWeight5': float,
                    'FuelFlowWeight6': float,
                    'FuelFlowWeight7': float,
                    'FuelFlowWeight8': float,
                    'FuelFlowWeight9': float,
                    'FuelFlowVolume': float,
                    'FuelFlowVolume1': float,
                    'FuelFlowVolume2': float,
                    'FuelFlowVolume3': float,
                    'FuelFlowVolume4': float,
                    'FuelFlowVolume5': float,
                    'FuelFlowVolume6': float,
                    'FuelFlowVolume7': float,
                    'FuelFlowVolume8': float,
                    'FuelFlowVolume9': float,
                    'RadarMode': float,
                    'RadarAzimuth': float,
                    'RadarElevation': float,
                    'RadarRoll': float,
                    'RadarRange': float,
                    'RadarHorizontalBeamwidth': float,
                    'RadarVerticalBeamwidth': float,
                    'LockedTargetMode': float,
                    'LockedTargetAzimuth': float,
                    'LockedTargetElevation': float,
                    'LockedTargetRange': float,
                    'EngagementMode': float,
                    'EngagementMode2': float,
                    'EngagementRange': float,
                    'EngagementRange2': float,
                    'VerticalEngagementRange': float,
                    'VerticalEngagementRange2': float,
                    'RollControlInput': float,
                    'PitchControlInput': float,
                    'YawControlInput': float,
                    'RollControlPosition': float,
                    'PitchControlPosition': float,
                    'YawControlPosition': float,
                    'RollTrimTab': float,
                    'PitchTrimTab': float,
                    'YawTrimTab': float,
                    'AileronLeft': float,
                    'AileronRight': float,
                    'Elevator Rudder': float,
                    'PilotHeadRoll': float,
                    'PilotHeadPitch': float,
                    'PilotHeadYaw': float,
                    'VerticalGForce': float,
                    'LongitudinalGForce': float,
                    'LateralGForce': float,
                    'ENL': float,
                    'Latitude': float,
                    'Longitude': float,
                    'Altitude': float,
                    'Pitch': float,
                    'Yaw': float, 
                    'Roll': float,
                    'U': float,
                    'V': float,
                    'Heading': float}

PROPERTIES = GLOBAL_PROPERTIES.copy()
PROPERTIES.update(OBJECT_PROPERTIES)

TR1 = ['Longitude', 'Latitude', 'Altitude']
TR2 = ['Longitude', 'Latitude', 'Altitude', 'U', 'V']
TR3 = ['Longitude', 'Latitude', 'Altitude', 'Roll', 'Pitch', 'Yaw']
TR4 = ['Longitude', 'Latitude', 'Altitude', 'Roll', 'Pitch', 'Yaw', 'U', 'V', 'Heading']

TRANSFORMATION_PROPERTIES = {3: TR1, 5: TR2, 6: TR3, 9: TR4}